fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppetserver_gem: "https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
  symlinks:
    autosign: "#{source_dir}"
